<!-- Topbar Start -->
<?php include('header.php'); ?>
<!-- Topbar End -->




        <!-- CONTENT START -->
        <div class="page-content">

            <!-- INNER PAGES BANNER START -->
            <div class="sx-bnr-inr overlay-wraper bg-parallax bg-top-center" data-stellar-background-ratio="0.5"
                style="background-image: url('https://theme7x.com/inteshape/images/banner/6.jpg'); background-position: 50% -50px;">
                <div class="overlay-main bg-black opacity-07"></div>
                <div class="container">
                    <div class="sx-bnr-inr-entry">
                        <div class="banner-title-outer">
                            <div class="banner-title-name">
                                <h2 class="m-tb0">Contact Us</h2>
                                <!-- <p>
                                The essence of interior design will always be about people and how they live. It is
                                about the realities of what makes for an attractive, civilized.
                            </p> -->
                            </div>
                        </div>
                        <!-- BREADCRUMB ROW -->

                        <div>
                            <ul class="sx-breadcrumb breadcrumb-style-2">
                                <li><a href="index.html">Home</a></li>
                                <li>Contact Us</li>
                            </ul>
                        </div>

                        <!-- BREADCRUMB ROW END -->
                    </div>
                </div>
            </div>
            <!-- INNER PAGES BANNER END -->





            

            <!-- CTA START -->
            <div class="cta-inner-area bg_image ptb--120">
                <div class="container-full">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="cta-main-two">
                                <div class="pre-title-area">
                                    <!-- <img src="assets/images/about/02.png" alt="about"> -->
                                    <span class="pre-title">Call to Action</span>
                                </div>
                                <h2 class="title">Have a Project in mind? <br>
                                    Do not hesitate to say hello.</h2>
                                <a href="#" class="rts-btn  btn-border radious-3 mt--50 ">Let’s Build<i
                                        class="fa fa-arrow-right p-l10"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- CTA END -->


        </div>
        <!-- CONTENT END -->






<!-- Footer Start -->
<?php include('footer.php'); ?>
<!-- Footerr End -->